# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2024-10-30 18:38+0800\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"


#: D:\Users\pinec\Documents\Code\python\musicatri1\src\app.py:23
msgid "Musicatri run successfully"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\app.py:29
msgid "development mode is on, know more about development mode at README.md"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\app.py:75
msgid "Failed in connecting database : %(error)s"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\client\implement\discord_client_impl.py:15
msgid "exception occur while fetch discord user information: %(exception)s"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\client\implement\discord_client_impl.py:27
msgid "successfully fetch user"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\client\implement\discord_client_impl.py:32
msgid "exception occur while acquiring discord oauth2 credential: %(exception)s"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\client\implement\discord_client_impl.py:36
msgid "cannot acquire token without code"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\client\implement\discord_client_impl.py:72
msgid "successfully acquire token"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\config\cors_configuration.py:14
msgid "enable cors for all router"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\config\exception_configuration.py:18
msgid "404_resource_not_found: %s"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\config\exception_configuration.py:29
msgid "500_internal_server_error: %s"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\config\exception_configuration.py:55
msgid "business_exception_occur: %s"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\config\exception_configuration.py:82
msgid "system_exception_occur: %s"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\config\exception_configuration.py:100
msgid "unknown_exception_occur: %s"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\controller\static_controller.py:14
msgid "static resource path locate in: %s"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\decorator\controller_decorator.py:39
msgid "route logging: %(route_path)s : %(log_message)s"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\decorator\controller_decorator.py:62
msgid "route time consuming: %(route_path)s : %(time_consuming).6f seconds"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\decorator\controller_decorator.py:85
msgid "route_timeout: %(route_path)s : %(time_consuming).6f seconds, higher than setting threshold %(threshold).6f seconds"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\decorator\controller_decorator.py:105
msgid "route_event_triggered: %(route_path) : %(event_name)"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\decorator\exception_decorator.py:50
msgid "logged an exception occur : %(exception)s"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\discord_bot\atri.py:37
msgid "atri hibernate"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\discord_bot\atri.py:69
msgid "atri started"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\discord_bot\atri.py:79
msgid "atri start failed, got loging failure: %(exception)s"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\discord_bot\atri.py:82
msgid "atri start failed, got HTTP exception: %(exception)s"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\discord_bot\atri.py:85
msgid "atri start failed, got client connection error: %(exception)s"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\discord_bot\atri.py:88
msgid "atri start failed, got unknown error: %(exception)s"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\discord_bot\atri.py:97
msgid "atri start successfully"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\discord_bot\atri.py:100
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\discord_bot\atri.py:101
msgid "atri has already stopped"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\discord_bot\atri.py:114
msgid "atri is in awaiting state"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\discord_bot\atri.py:169
msgid "initializing musicatri facade"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\repository\mongodb\mapper\profile_mapper_impl.py:69
msgid "discord user abs error: cannot inserting data %(data)s, 'id' is invalid"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\repository\mongodb\mapper\session_mapper_impl.py:61
msgid "discord oauth session abs error: cannot inserting data %(data)s, 'id' is invalid"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\repository\mongodb\mongodb_client.py:28
msgid "initializing mongo client..."
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\repository\mongodb\mongodb_client.py:34
msgid "MongodbClient initialization error: invalid prototype : %(prototype)s, fallback to 'mongo' as prototype"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\repository\mongodb\mongodb_client.py:40
msgid "MongodbClient initialization error: invalid host : %(host)s, fallback to '127.0.0.1' as host"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\repository\mongodb\mongodb_client.py:46
msgid "MongodbClient initialization error: invalid port : %(port)s, fallback to '27017' as port"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\repository\mongodb\mongodb_client.py:52
msgid "MongodbClient initialization error: invalid database name : cannot be none or empty string, fall back to 'musicatri' as database name "
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\repository\mongodb\mongodb_client.py:58
msgid "successfully build mongo client: host: %(host)s, port: %(port)s, username: %(username)s, password: %(password)s"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\repository\mongodb\mongodb_entity_adaptor.py:30
msgid "mongo entity adaptor error: %(clazz)s must be a subclass of BaseEntity"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\repository\mongodb\transaction_manager_impl.py:40
msgid "error occur while rollback transaction: %(error)s"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\base_service\implement\permission_service_impl.py:29
msgid "permission table got error status, reinitialize table..."
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\base_service\implement\permission_service_impl.py:33
msgid "done initializing permission table, %(count)s documents inserted"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\base_service\implement\session_service_impl.py:50
msgid "failed in updating user jwt session"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\base_service\implement\session_service_impl.py:56
msgid "failed in inserting user jwt session"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\base_service\implement\session_service_impl.py:85
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:186
msgid "Invalid token: missing userid"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\atri_service_impl.py:16
msgid "connecting musicatri to discord server..."
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\atri_service_impl.py:20
msgid "atri run successfully"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:37
msgid "current using language: %(lang)s"
msgstr "当前使用语言: %(lang)s"

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:53
msgid "login params not support, allow code, access_token or refresh token"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:60
msgid "authenticate successful"
msgstr "认证成功"

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:207
msgid "DiscordOAuthStrategy.authenticate need to be run with transaction"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:214
msgid "request did not container 'code' as a parameter"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:251
msgid "avoiding blocked discord account login, discord account id is : '%(user_id)s'"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:252
msgid "this discord account have been blocked"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:265
msgid "failed in updating discord oauth2 session information for user '%(user_id)s'"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:287
msgid "failed in updating jwt session information for user '%(user_id)s'"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:300
msgid "failed in inserting discord user information for user '%(user_id)s'"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:307
msgid "failed in initiating permission level for user '%(user_id)s')'"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:323
msgid "failed in inserting discord session information for user '%(user_id)s'"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\auth_service_impl.py:346
msgid "failed in inserting user jwt session information for user '%(user_id)s'"
msgstr ""

#:
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\service\upper_service\implement\system_service_impl.py:30
msgid "service_healthy"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:66
#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:83
msgid "operation successfully"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:69
msgid "client error"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:70
msgid "resource not found"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:71
msgid "invalid request params"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:72
msgid "authentication.py failed"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:73
msgid "permission denied"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:74
msgid "token expired"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:75
msgid "token invalid"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:76
msgid "token session has been closed"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:79
msgid "internal server error"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:84
msgid "operation error"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:85
msgid "awaiting"
msgstr ""

#: D:\Users\pinec\Documents\Code\python\musicatri1\src\utils\result.py:86
msgid "unknown"
msgstr ""

